# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import chat_rpg_client
from chat_rpg_client.api.users_api import UsersApi  # noqa: E501
from chat_rpg_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = chat_rpg_client.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user(self):
        """Test case for create_user

        Create User  # noqa: E501
        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        Delete User  # noqa: E501
        """
        pass

    def test_get_all_users(self):
        """Test case for get_all_users

        All Users  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        Update User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
