# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import chat_rpg_client
from chat_rpg_client.api.users_api import UsersApi  # noqa: E501
from chat_rpg_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = chat_rpg_client.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_users_get(self):
        """Test case for users_users_get

        Get Users  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
