# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import chat_rpg_client
from chat_rpg_client.api.campaigns_api import CampaignsApi  # noqa: E501
from chat_rpg_client.rest import ApiException


class TestCampaignsApi(unittest.TestCase):
    """CampaignsApi unit test stubs"""

    def setUp(self):
        self.api = chat_rpg_client.api.campaigns_api.CampaignsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_campaign(self):
        """Test case for create_campaign

        Create Campaign  # noqa: E501
        """
        pass

    def test_delete_campaign(self):
        """Test case for delete_campaign

        Delete Campaign  # noqa: E501
        """
        pass

    def test_get_all_campaigns(self):
        """Test case for get_all_campaigns

        All Campaigns  # noqa: E501
        """
        pass

    def test_update_campaign(self):
        """Test case for update_campaign

        Update Campaign  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
