# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import chat_rpg_client
from chat_rpg_client.api.messages_api import MessagesApi  # noqa: E501
from chat_rpg_client.rest import ApiException


class TestMessagesApi(unittest.TestCase):
    """MessagesApi unit test stubs"""

    def setUp(self):
        self.api = chat_rpg_client.api.messages_api.MessagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_message(self):
        """Test case for delete_message

        Delete Message  # noqa: E501
        """
        pass

    def test_send_message(self):
        """Test case for send_message

        Send Message  # noqa: E501
        """
        pass

    def test_update_message(self):
        """Test case for update_message

        Update Message  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
