# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import chat_rpg_client
from chat_rpg_client.models.campaign_create import CampaignCreate  # noqa: E501
from chat_rpg_client.rest import ApiException

class TestCampaignCreate(unittest.TestCase):
    """CampaignCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CampaignCreate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CampaignCreate`
        """
        model = chat_rpg_client.models.campaign_create.CampaignCreate()  # noqa: E501
        if include_optional :
            return CampaignCreate(
                name = None
            )
        else :
            return CampaignCreate(
                name = None,
        )
        """

    def testCampaignCreate(self):
        """Test CampaignCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
